# Generated by Django 4.1.5 on 2023-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_pg_id_order_pg_response_order_pg_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
